import Footer from '../components/footer';
import Header from '../components/header';
import './globals.css';
import PropTypes from 'prop-types';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({children}) {
	return (
		<html lang='en'>
			<body className='bg-white text-slate-900'>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
RootLayout.propTypes = {
	children: PropTypes.node,
};
